// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRlbe5QpP8uH9uleCNwKXs10wr8skUY4Y',
    appId: '1:15515497931:web:0cb1681cc69da92c2af24e',
    messagingSenderId: '15515497931',
    projectId: 'flutterfirebase-e11ae',
    authDomain: 'flutterfirebase-e11ae.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-e11ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-e11ae.appspot.com',
    measurementId: 'G-0JY8J0JT94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYajizULQf6k5XzA0omyI_x02UTQnBc74',
    appId: '1:15515497931:android:3e0a8f0242ae15292af24e',
    messagingSenderId: '15515497931',
    projectId: 'flutterfirebase-e11ae',
    databaseURL: 'https://flutterfirebase-e11ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-e11ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDziRXUst_tLGdJg91xDG6na9ABEitRBlo',
    appId: '1:15515497931:ios:8145f4b4c76a948c2af24e',
    messagingSenderId: '15515497931',
    projectId: 'flutterfirebase-e11ae',
    databaseURL: 'https://flutterfirebase-e11ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-e11ae.appspot.com',
    androidClientId: '15515497931-2vn9469lpuph8kee78lpk8eo5anfukpl.apps.googleusercontent.com',
    iosClientId: '15515497931-b7m3o1c1mndrdp8p65igbo6vs6738v5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.productApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDziRXUst_tLGdJg91xDG6na9ABEitRBlo',
    appId: '1:15515497931:ios:8145f4b4c76a948c2af24e',
    messagingSenderId: '15515497931',
    projectId: 'flutterfirebase-e11ae',
    databaseURL: 'https://flutterfirebase-e11ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-e11ae.appspot.com',
    androidClientId: '15515497931-2vn9469lpuph8kee78lpk8eo5anfukpl.apps.googleusercontent.com',
    iosClientId: '15515497931-b7m3o1c1mndrdp8p65igbo6vs6738v5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.productApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpDhN2-VU7euourn18vkLqa4cu_UKo0tA',
    appId: '1:15515497931:web:0ce603708dd633202af24e',
    messagingSenderId: '15515497931',
    projectId: 'flutterfirebase-e11ae',
    authDomain: 'flutterfirebase-e11ae.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-e11ae-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-e11ae.appspot.com',
    measurementId: 'G-H6XBRGMDWY',
  );
}
